### ISSUE TITLE
Error in beam search method with certain examples

### ISSUE THREAD

**Issue by saminahbab** [nicola-decao/efficient-autoregressive-EL#2]
Hey Nic, 

Just having some trouble trying to get this model running on something other than the example. 
I see that there may be a potential bug. 

The example provided by the repo about cricket is working on my local machine. 

I have also given an input sentence from a news article: 

`When Fabien needed to have a decayed tooth removed in May, his dentist told him that he would have to wait up to three years to have it done on the NHS. In disbelief, the 27-year-old from Edinburgh rang 50 dental practices but without any luck. He had no choice but to go private.`

which results in output: 

`[[(5, 11, [('Fabrizio Ravanelli', -2.598557949066162), ('Bernard Tapie', -3.688422918319702), ('Bernard F. Fisher', -9.065004348754883), ('Fabrizio Brienza', -9.414182662963867), ('Fabrizio Guidi', -17.98088264465332)]), (188, 197, [('Edinburgh', -2.414118766784668), ('Edmonton', -3.213533401489258), ('Scotland', -3.43752121925354), ('Atlanta', -4.544315338134766), ('York', -5.995124340057373)])]]`

however, this sentence: 
`Boris Johnson believed to have overruled ministers unwilling to compromise on post-Brexit immigration as forecourt queues mount.`

results in the following error: 

`
Traceback (most recent call last):
  File "/home/samin/src/efficient-autoregressive-EL/test.py", line 23, in <module>
    output = model.sample([s])
  File "/home/samin/src/efficient-autoregressive-EL/src/model/efficient_el.py", line 455, in sample
    spans = self.forward_beam_search(batch)
  File "/home/samin/src/efficient-autoregressive-EL/src/model/efficient_el.py", line 292, in forward_beam_search
    tokens, scores_el = self.entity_linking.forward_beam_search(
  File "/home/samin/src/efficient-autoregressive-EL/src/model/entity_linking.py", line 321, in forward_beam_search
    tokens, lm_scores, all_contexts = beam_search(
  File "/home/samin/src/efficient-autoregressive-EL/src/beam_search.py", line 78, in beam_search
    hidden = tile(hidden, beam_width, dim=0)  # [layers, B*beam_width, H_dec]
  File "/home/samin/src/efficient-autoregressive-EL/src/beam_search.py", line 20, in tile
    return [tile(e, count, dim=dim) for e in x]
  File "/home/samin/src/efficient-autoregressive-EL/src/beam_search.py", line 20, in <listcomp>
    return [tile(e, count, dim=dim) for e in x]
  File "/home/samin/src/efficient-autoregressive-EL/src/beam_search.py", line 30, in tile
    x.view(batch, -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous
`

I was wondering if you have seen this issue before?

**Comment by nicola-decao** [comment]
Hi @saminahbab I believe this happens because the model didn't find any mention and therefore when it comes to the beam search function there is a tensor with size 0. I fixed it now.

**Comment by saminahbab** [comment]
@nicola-decao, That makes sense. 
I can confirm that it is now working for me. Cheers for that!
