### ISSUE TITLE
trainer.test(model) produces an error when resuming from checkpoint. 

### ISSUE THREAD

**Issue by martinritchie** [nicola-decao/efficient-autoregressive-EL#3]
Hey, 

Thank you for sharing your code, it has been straightforward to train a model on my own data. 

When I attempt to run `trainer.test(model)` with the command: `python ./scripts/trainer.py --resume_from_checkpoint /path/to/checkpoint/ --gpus=1` I receive the following error: 

```
Testing: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "scripts/train.py", line 47, in <module>
    trainer.test(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 705, in test
    results = self._run(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _dispatch
    self.accelerator.start_evaluating(self)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 95, in start_evaluating
    self.training_type_plugin.start_evaluating(trainer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 165, in start_evaluating
    self._results = trainer.run_stage()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 997, in run_stage
    return self._run_evaluate()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1083, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 111, in advance
    output = self.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 154, in evaluation_step
    output = self.trainer.accelerator.test_step(step_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 226, in test_step
    return self.training_type_plugin.test_step(*step_kwargs.values())
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 181, in test_step
    return self.model.test_step(*args, **kwargs)
  File "/code/efficient-autoregressive-EL/src/model/efficient_el.py", line 450, in test_step
    self.log_dict(metrics)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 507, in log_dict
    self.log(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 446, in log
    results.log(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py", line 472, in log
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: You called `self.log(micro_f1, ...)` twice in `test_step` with different arguments. This is not allowed
```

Am I using the trainer's `test` method incorrectly? 

Thank you, 

Martin

**Comment by nicola-decao** [comment]
Probably you are using the latest version of `pytorch-lightning` where I used `1.2`. Now I should be fixed by 85c0b232c3294eed8a8faa0744324903e50155cf
